require('dealuhguurl.settings')
require('dealuhguurl.packer')
require('dealuhguurl.lsp')
require('dealuhguurl.cmp')
require('dealuhguurl.treesitter')
require('dealuhguurl.auto-pairs')
require('dealuhguurl.impatient')
require('dealuhguurl.telescope')
require('dealuhguurl.markdown')

