#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_motion_interval 7ms


xcompmgr &
feh --bg-fill ~/Downloads/wallpapers/helmet.webp &
xrandr --output HDMI-0 --mode 1920x1080 --rate 144.00 --primary
polybar &

